### ISSUE TITLE
IOB-Format

### ISSUE THREAD

**Issue by JanFreise** [asahi417/tner#27] opened 2022-08-15 17:14 UTC
Hello and thank very much for the new TNER-Version. :)

It seems like the old syntax/bibs (e.g. "from tner import TrainTransformersNER") have been discontinued in the new release?
(btw: you have 4 Colab Notepad-Files on your homepage that still reference these and they are also not working anymore).

I tried calling the new GridSearcher-Syntax, with my old local dataset in IOB-Format (train.txt & valid.txt), which worked fine usind the previous TNER-Version.

This O
is O
the O
first O
Entity B-SOMETHING
. 0

This crashes with error message "JSONDecodeError: Expecting value: line 1 column 1 (char 0)" because the program is looking for the label-file which isnt present. So is IOB (or BIO) no longer supported and i have to convert my data into your json-format?

Thanks, 
Jan

searcher = GridSearcher(
   checkpoint_dir='./ckpt_tner',
   dataset="data/iob",  # either of `dataset` (huggingface dataset) or `local_dataset` (custom dataset) should be given
   model="roberta-large",  # language model to fine-tune
   epoch=10,  # the total epoch (`L` in the figure)
   epoch_partial=5,  # the number of epoch at 1st stage (`M` in the figure)
   n_max_config=3,  # the number of models to pass to 2nd stage (`K` in the figure)
   batch_size=16,
   gradient_accumulation_steps=[4, 8],
   crf=[True, False],
   lr=[1e-4, 1e-5],
   weight_decay=[None, 1e-7],
   random_seed=[42, 442],
   lr_warmup_step_ratio=[None, 0.1],
   max_grad_norm=[None, 10]  
)
searcher.train()

**Comment by asahi417** [comment] 2022-08-15 17:58
Hi thank you so much to try the new T-NER! We still support IOB-format but the way to pass the files is now a bit different.  The old version accepted a directly to the IOB files, but now we let user to pass a dictionary where it contains path to each split. eg)
```
{
    "train": "examples/local_dataset_sample/train.txt",
    "valid": "examples/local_dataset_sample/train.txt",
    "test": "examples/local_dataset_sample/test.txt"
}
```
https://github.com/asahi417/tner/blob/master/README.md#custom-dataset

So to run grid search with local dataset would look like below
```
searcher = GridSearcher(
checkpoint_dir='./ckpt_tner',
# dataset="data/iob", # either of dataset (huggingface dataset) or local_dataset (custom dataset) should be given
local_dataset={
    "train": "examples/local_dataset_sample/train.txt",
    "valid": "examples/local_dataset_sample/train.txt",
    "test": "examples/local_dataset_sample/test.txt"
},
model="roberta-large", # language model to fine-tune
epoch=10, # the total epoch (L in the figure)
epoch_partial=5, # the number of epoch at 1st stage (M in the figure)
n_max_config=3, # the number of models to pass to 2nd stage (K in the figure)
batch_size=16,
gradient_accumulation_steps=[4, 8],
crf=[True, False],
lr=[1e-4, 1e-5],
weight_decay=[None, 1e-7],
random_seed=[42, 442],
lr_warmup_step_ratio=[None, 0.1],
max_grad_norm=[None, 10]
)
searcher.train()
```

Also, thank you for pointing out the colab notebooks. I will update it soon as possible!

**Comment by JanFreise** [comment] 2022-08-15 18:25
Thanks! Working now..another case of RTFM... :)

The dataset now get validateds and pre-processed in the new version. 
Two quick questions on that if i may:

WARNING:root:skip ['O']: too short 
>> this seems alright i guess this was just a TABULATOR O

WARNING:root:skip word # from ['#', 'O']: STOPWORDS
i guess this is an error in my span-size ?
C-Sharp is saved as two individual words

C B-Skill
# I-SKill

This can only work as C# B-SKILL for you will remove single # and other declared stopword?

**Comment by asahi417** [comment] 2022-08-15 18:31
That's a really good point... I haven't explained it in README at all, but the dataset script contains a built-in stopword list (can be found here https://github.com/asahi417/tner/blob/master/tner/get_dataset.py#L14 ) as some public datasets use those symbols to specify noisy words. I think it would make sense to have an option to deactivate this stopword.

**Comment by asahi417** [comment] 2022-08-15 18:33
WARNING:root:skip ['O']: too short

This happens when your IOB file contain single column. It should always have a word and its associated tag as below.

```
I O
live O
in O
London B-LOC
```

But not
```
I
live
in
London B-LOC
```

**Comment by asahi417** [comment] 2022-08-15 18:37
I noticed that the stopword (and the stoptags) were a legacy code from the previous version, and nothing to do with the latest TNER so I just removed it.

**Comment by JanFreise** [comment] 2022-08-15 18:40
> That's a really good point... I haven't explained it in README at all, but the dataset script contains a built-in stopword list (can be found here https://github.com/asahi417/tner/blob/master/tner/get_dataset.py#L14 ) as some public datasets use those symbols to specify noisy words. I think it would make sense to have an option to deactivate this stopword.

and/or save the stopword list seperated from the code as txt-file so one can customize it to ones needs. 

I literally can't have single columns because the tags are all associated to an identified token. i just scrolled through the text-file and i don't have an entry consisting of just a single "O.

**Comment by JanFreise** [comment] 2022-08-15 18:58
hello again, sorry i got one more question

"use_auth_token" needs to pass a authentication-string to the huggingsface-repo. 
it seems its defined as boolean datatype only?

https://huggingface.co/docs/hub/security-tokens

**Comment by asahi417** [comment] 2022-08-15 19:37
In terms of the use_auth_token, I believe huggingface recommends to login to your account in your terminal by either of `huggingface-cli login` or `transformers-cli login` where you are prompted to input the api token. If use_auth_token is True, huggingface libraries will check the api token stored at your local environment, so that you don't have to pass the api token in your script. 

However, they actively update the scheme for signing up, so maybe I'm wrong :(

**Comment by asahi417** [comment] 2022-08-15 19:38
Would you be able to share the IOB file in which the skip occurs? I can take a look it locally to see what causes the skip

**Comment by asahi417** [comment] 2022-09-26 18:15
Hi Jan,

Can you confirm whether you can load the custom dataset with the latest version? As I mentioned in the email, the issue of having so many warning message to skip many lines is caused by the unrecognizable character (such as the one in the line 3250 of the train.txt file). When python performs `text.split()`, those characters are ignored and that’s why there’s only “O” left in such a case. I fixed this issue by normalizing the character into uff-8, so now you should be able to load the dataset properly. So now you should be able to load the dataset. At least, it worked for me.

**Comment by asahi417** [comment] 2022-09-28 19:04
We confirmed that the IOB formatting was solved but there is another issue, which has nothing to do with the format, so I'll close this.

**Closed** 2022-09-28 19:04 UTC
